#!/usr/bin/env bash
# Install a page
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
redirect="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "19i $redirect" /etc/nginx/site-available/default
service nginx restart
