#!/usr/bin/env bash
# Fix the port
rm /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on;/;/g" /etc/nginx/sites-available/default
ln /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
