#!/usr/bin/env bash
# This script is displaying "Holberton School" and the 9th time say Hi
i=0
while ((i < 10)); do
    if [ "$i" = 9 ]
    then
        echo "Hi"
    fi
        echo "Holberton School"
    ((i += 1))
done