#!/usr/bin/env bash
# This script is displaying "Holberton School" in 8 times but in 4th and 8th time not
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i += 1))
done