#!/usr/bin/env bash
# This script displays numbers 1 to 20 and change the numbers 4, 9, 17
HOUR=0
MINU=1
while [ $HOUR -le 12 ]
do
    echo "Hour: $HOUR"
    while [ $MINU -le 59 ]
    do
        echo $MINU
        ((MINU += 1))
    done
    MINU=1
    ((HOUR += 1))
done