#!/usr/bin/env bash
# This script displays hours from 0 to 12 and minutes from 1 to 59
HOUR=0
MINU=1
while [ $HOUR -le 12 ]
do
    echo "Hour: $HOUR"
    while [ $MINU -le 59 ]
    do
        echo $MINU
        ((MINU += 1))
    done
    MINU=1
    ((HOUR += 1))
done